### ISSUE TITLE
ovirt_auth received error "ovirtsdk4 version 4.4.0 or higher is required for this module" with Python3

### ISSUE THREAD

**Issue by dewongway** [oVirt/ovirt-ansible-collection#126]
I'm running Red Hat Linux 7.7 and trying to connect to and create VMs on Red Hat Virtualization 4.3.10. When I call the module ovirt_auth in a playbook using python 2.7, the module works but it would fail if I switch to Python 3.6.8. I couldn't figure out why it's not working with Python 3.6.8

```
TASK [Obtain SSO token with using username/password credentials] ************************************************************************************************************************************************************************
task path: /stage/ansible/rhv/create-ovirt-vm.yml:27
Using module file /stage/ansible/collections/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_auth.py
Pipelining is enabled.
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_file": "ca.pem",
            "compress": true,
            "headers": null,
            "hostname": null,
            "insecure": null,
            "kerberos": false,
            "ovirt_auth": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "timeout": 0,
            "token": null,
            "url": "https://server/ovirt-engine/api",
            "username": "admin@internal"
        }
    },
    "msg": "ovirtsdk4 version 4.4.0 or higher is required for this module"
}
Read vars_file 'engine_vars.yml'
```

The ansible and ovirt-engine-sdf-python 4.4.4 are installed with pip and pip3. 

```
[root@rhv-ansible2 rhv]# pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Package                      Version
---------------------------- ----------
ansible                      2.9.13
Babel                        0.9.6
backports.ssl-match-hostname 3.5.0.1
Beaker                       1.5.4
certifi                      2019.11.28
cffi                         1.6.0
chardet                      3.0.4
configobj                    4.7.2
cryptography                 1.7.2
decorator                    3.4.0
enum34                       1.0.4
ethtool                      0.8
httplib2                     0.9.2
idna                         2.8
iniparse                     0.4
ipaddr                       2.1.11
ipaddress                    1.0.16
Jinja2                       2.7.2
jmespath                     0.9.0
kitchen                      1.1.1
lxml                         3.2.1
M2Crypto                     0.21.1
Magic-file-extensions        0.2
Mako                         0.8.1
MarkupSafe                   0.11
matplotlib                   1.2.0
nfsometer                    1.7
NFStest                      2.1.5
nose                         1.3.7
numpy                        1.7.1
ovirt-engine-sdk-python      4.4.4
paramiko                     2.1.1
passlib                      1.6.5
Paste                        1.7.5.1
pciutils                     1.7.3
perf                         0.1
pip                          20.2.3
ply                          3.4
pyasn1                       0.1.9
pycparser                    2.14
pycurl                       7.19.0
pygobject                    3.22.0
pygpgme                      0.3
pyinotify                    0.9.4
pyliblzma                    0.5.3
pyOpenSSL                    0.13.1
pyparsing                    1.5.6
PyPowerStore                 1.0.0.0
python-dateutil              1.5
python-dmidecode             3.10.13
python-linux-procfs          0.4.9
pytz                         2016.10
pyudev                       0.15
pyvmomi                      6.7.3
pyxattr                      0.5.1
PyYAML                       3.10
requests                     2.22.0
rhnlib                       2.5.65
schedutils                   0.4
setuptools                   0.9.8
six                          1.13.0
slip                         0.4.0
slip.dbus                    0.4.0
subscription-manager         1.24.13
syspurpose                   1.24.13
Tempita                      0.5.1
urlgrabber                   3.10
urllib3                      1.25.7
yum-metadata-parser          1.1.4
```

```
[root@rhv-ansible2 rhv]# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ansible (2.9.13)
certifi (2020.6.20)
cffi (1.14.3)
chardet (3.0.4)
cryptography (3.1)
idna (2.10)
Jinja2 (2.11.2)
MarkupSafe (1.1.1)
ovirt-engine-sdk-python (4.4.4)
pip (9.0.3)
pycparser (2.20)
pycurl (7.43.0.6)
pyOpenSSL (19.1.0)
pyvmomi (7.0)
PyYAML (5.3.1)
requests (2.24.0)
setuptools (39.2.0)
six (1.15.0)
urllib3 (1.25.10)
```

The ovirt.ovirt collection is installed from ansible galaxy.

**Comment by mnecas** [comment]
Hi,
don't recommend using pip it's not officially supported.

I have done some tests:
- created a blank container with el7
- installed pip and pip3
- for both versions installed ovirt-engine-sdk-python
- installed ansible first from rpm then pip and pip3
- installed collection from galaxy
- run the playbook multiple times and no issue
```console
[root@54ebf8d4344d ~]# pip list
ovirt-engine-sdk-python (4.4.4)
...
```
```console
[root@54ebf8d4344d ~]# pip3 list
ovirt-engine-sdk-python (4.4.4)
...
```

My bet is that the ansible does not even see the SDK.
Could you try: 
```python3
[root@54ebf8d4344d ~]# python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ovirtsdk4.version as sdk_version
>>> sdk_version.VERSION
'4.4.4'
```

**Comment by mwperina** [comment]
oVirt Ansible Collection is tested only with oVirt 4.4 and since oVirt 4.4 switched completely to CentOS 8, I highly recommend to do that same on your clients. Also as Martin mentioned we package everything as RPMs, so I highly recommend to use RPMs to install all of the dependencies and don't use other methods like pip.

If you want to stay with oVirt 4.3, then it's probably better to use oVirt Ansible Roles packaged as RPMs and distributed as a part of oVirt 4.3 release

**Comment by dewongway** [comment]
Thanks for the information. I'll look into moving to ovirt 4.4 and CentOS 8.

**Comment by mnecas** [comment]
Hi @dewongway, did the migration helped? Can I close the issue?

**Comment by D1Ck3n** [comment]
Hi, i have a similar issue:

`TASK [Obtain SSO token with using username/password credentials] ******************************************************************************************************************************************************************************
task path: /home/username/git/project/ovirt/run.yml:12
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060 `" && echo ansible-tmp-1644240275.3164217-222305061888060="` echo /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_auth.py
<localhost> PUT /root/.ansible/tmp/ansible-local-805802tnyo11/tmpb0n9_2lz TO /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060/AnsiballZ_ovirt_auth.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060/ /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060/AnsiballZ_ovirt_auth.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060/AnsiballZ_ovirt_auth.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1644240275.3164217-222305061888060/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_ovirt.ovirt.ovirt_auth_payload_eEE0jP/ansible_ovirt.ovirt.ovirt_auth_payload.zip/ansible_collections/ovirt/ovirt/plugins/modules/ovirt_auth.py", line 215, in <module>
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ca_file": "apicert.cer",
            "compress": true,
            "headers": null,
            "hostname": null,
            "insecure": null,
            "kerberos": false,
            "ovirt_auth": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "timeout": 0,
            "token": null,
            "url": "https://ovirtserver.company.com/ovirt-engine/api",
            "username": "username@domain"
        }
    },
    "msg": "ovirtsdk4 version 4.4.0 or higher is required for this module"
}
Read vars_file 'passwords.yml'
Read vars_file 'vars_vm.yml'

TASK [Always revoke the SSO token] ************************************************************************************************************************************************************************************************************
task path: /home/home/username/git/project/ovirt/run.yml:63
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ovirt_auth' is undefined\n\nThe error appears to be in '/home/home/username/git/project/ovirt/run.yml': line 63, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      always:\n        - name: Always revoke the SSO token\n          ^ here\n"
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=2    skipped=0    rescued=0    ignored=0   
`

the strange thing is: i run this on Linux Mint 20.3 and it failes, do i run it on a ubuntu 20.04 it works. Both have the same packages installed

**Comment by D1Ck3n** [comment]
i tried this:

```
username@ad.company.to:~/git/project/ovirt$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ovirtsdk4.version as sdk_version
>>> sdk_version.VERSION
'4.5.0'
>>> 
```
or what did you mean?

**Comment by mnecas** [comment]
And which version does ansible use? `ansible --version`

**Comment by D1Ck3n** [comment]
```
$ ansible --version
ansible 2.9.6
  config file = /home/user/git/project/ovirt/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

**Comment by mnecas** [comment]
Ahh sorry don't know that from the top of my head but I think that is the issue.
This is really hard to debug because the each system cloud have different settings and could be broken on different places

**Comment by D1Ck3n** [comment]
i found a solution for me! :) 
first i add `interpreter_python = /usr/bin/python3` to my ansible.cfg to enforce it, but it also works just uninstalling python2
