### ISSUE TITLE
Ovirt ansible RPMs support for zLinux(s390x) architecture.

### ISSUE THREAD

**Issue by dpkulkarni** [oVirt/ovirt-ansible-collection#137]
##### SUMMARY
I am working on building https://github.com/ManageIQ/manageiq on s390x architecture for which I need the `ovirt-ansible` RPMs on s390x arch which are missing at this link `https://resources.ovirt.org/pub/ovirt-4.4/rpm/el8/`

##### COMPONENT NAME
ovirt-ansible RPMs

These are the RPMs which I have build using the src.rpm on s390x, these have to be added to the RPM repo along with `ppc64le` and `x86_64
```
# ll ovirt*
ovirt-ansible-cluster-upgrade-1.2.3-1.el8.noarch.rpm
ovirt-ansible-disaster-recovery-1.3.0-1.el8.noarch.rpm
ovirt-ansible-engine-setup-1.2.4-1.el8.noarch.rpm
ovirt-ansible-hosted-engine-setup-1.1.8-1.el8.noarch.rpm
ovirt-ansible-image-template-1.2.2-1.el8.noarch.rpm
ovirt-ansible-infra-1.2.2-1.el8.noarch.rpm
ovirt-ansible-manageiq-1.2.1-1.el8.noarch.rpm
ovirt-ansible-repositories-1.2.5-1.el8.noarch.rpm
ovirt-ansible-roles-1.2.3-1.el8.noarch.rpm
ovirt-ansible-shutdown-env-1.1.0-1.el8.noarch.rpm
ovirt-ansible-vm-infra-1.2.3-1.el8.noarch.rpm
```

**Comment by dpkulkarni** [comment]
@mnecas Do you have any comments on the above request to include RPMs for s390x?

**Comment by mwperina** [comment]
Hi Deepak,

sorry for taking it a bit long, we needed to clarify several things. So here are my comments:

1. All above mentioned packages are noarch, so even though we are building them on x86_64 machines, they should be installable on all architectures. So unless I'm missing something you should be able to include existing RPM packages into s390x ManageIQ build
2. CI of oVirt project doesn't contain any s390x machines and officially we don't support s390x architecture. oVirt engine is supported on CentOS 8 on x86_64 and oVirt hypervisors on CentOS 8 on x86_64 and ppc64le architectures
3. We are currently moving all supported oVirt Ansible roles into oVirt Ansible Collection, where all future development will continue. So if you are going to include oVirt Ansible Roles in future versions of ManageIQ, it makes sense for you to use oVirt Ansible Collection instead (RPM package with the 1st stable release should be available till end of October along with releasing to Ansible Galaxy)

Regards,
Martin

**Comment by dpkulkarni** [comment]
@mnecas 

Thanks for your response. 

1. Yes these are the noarch packages that I built using these .SRPMs https://resources.ovirt.org/pub/ovirt-4.4/rpm/el8/SRPMS/ I built on s390x machine but not sure why the noarch RPMs getting build 

2. May be I can check if there is any s390x machine available for the community use.

3. For this point I need to check with ManageIQ dev team

**Comment by mnecas** [comment]
The manageiq role is being deprecated in the next version of the collection.
