### ISSUE TITLE
Manageiq: CFME database is not configured while running ovirt.manageiq role

### ISSUE THREAD

**Issue by mguetta1** [oVirt/ovirt-ansible-collection#153]
Running ovirt.manageiq role in order to deploy CFME in RHV engine fails on CFME database configuration.
The role is running as described here: https://github.com/oVirt/ovirt-ansible-manageiq#example-playbook
It seems like something got broke within it as the DB configuration fails for CFME versions that were successfully installed in the past.
Link to failed build: https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/v2v-pipeline-mguetta/444/console

Error:
TASK [oVirt.manageiq : Start ManageIQ server] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service evmserverd: host"}

Workaround: configure CFME database manually

**Comment by mwperina** [comment]
manageiq roles has been deprecated in ovirt-ansible-collection 1.6.6 and it is going to be completely removed in 2.0.0 release, so closing as WONTFIX
