### ISSUE TITLE
Ovirt hosted-engine-setup cannot detect FC lun id

### ISSUE THREAD

**Issue by fatihkc** [oVirt/ovirt-ansible-collection#171]
##### SUMMARY

I tried to install hosted engine with Fibre Channel as storage domain but this ansible roles cannot assign variable. While selecting storage domain I can see my luns and ids of them but it keep saying 'value' parameter must be a string.

##### COMPONENT NAME

In ovirt-ansible-collection/roles/hosted_engine_setup/
In ovirt-ansible-collection/roles/hosted_engine_setup/defaults/main.yml 

[ INFO ] TASK [ovirt.hosted_engine_setup : Add Fibre Channel storage domain]
[ ERROR ] TypeError: The 'value' parameter must be a string
[ ERROR ] fatal: [localhost]: FAILED! => {"changed": false, "msg": "The 'value' parameter must be a string"}

##### STEPS TO REPRODUCE

Just try to install it with FC.

##### EXPECTED RESULTS

Add FC storage domain.

##### ACTUAL RESULTS

```
[ INFO ] TASK [ovirt.hosted_engine_setup : Add Fibre Channel storage domain]
[ ERROR ] TypeError: The 'value' parameter must be a string
[ ERROR ] fatal: [localhost]: FAILED! => {"changed": false, "msg": "The 'value' parameter must be a string"}

```
When it shows my lun id I change the In ovirt-ansible-collection/roles/hosted_engine_setup/defaults/main.yml. I change he_lun_id: null to my lun id then it works well. I tried both gui and cli but results are same.

Do you have any idea to fix this?

**Comment by kobihk** [comment]
it is probably related to one of the following bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1889953
https://bugzilla.redhat.com/show_bug.cgi?id=1891521

**Comment by arachmani** [comment]
@fatihkc Did you have a look at https://github.com/oVirt/ovirt-ansible-collection/issues/171#issuecomment-721230765 ?
If you still have an issue, can you please share the log files from var/log/ovirt-hosted-engine-setup/?

**Comment by fatihkc** [comment]
@arachmani I don't think they are relevant to this bug. I tried it with RHVH-4.4-20200930.0-RHVH-x86_64 which is newer. I cannot share log files because I don't have access to that environment anymore. Sorry about that.

**Comment by arachmani** [comment]
@fatihkc, Unfortunately, we are unable to help without the log files.
Please reopen/open a new issue if you encounter this again.

**Comment by graham-collinson** [comment]
I hit this issue with fibre recently.  It seems to be a problem when the lun id is all base-10 digits.
I have 2 installations.  1 engine deployment went fine but the 2nd one kept hitting this issue.
On my 2nd installation I ended up editing /usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py in LogicalUnitWriter to set the obj.id = "<mylunid>" just so I could get this deployed.
It turns out that the lun used for the 1st installation has hex letters in the lun id but the lun for the 2nd installation is made entirely of the digits 0-9.

I have logs available if needed but it would appear to be something to do with the handling of an all base-10 lun id?

I'm using:
python-ovirt-engine-sdk4-4.3.4-2.el7.x86_64
ovirt-hosted-engine-setup-2.3.13-1.0.1.el7.noarch

On Oracle Linux 7

**Comment by mwperina** [comment]
According to the api-model the type of id property is defined as string:

http://ovirt.github.io/ovirt-engine-api-model/4.4/#types/logical_unit

So could this be some incorrect conversion in ansible part?

**Comment by arachmani** [comment]
> I hit this issue with fibre recently. It seems to be a problem when the lun id is all base-10 digits.
> I have 2 installations. 1 engine deployment went fine but the 2nd one kept hitting this issue.
> On my 2nd installation I ended up editing /usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py in LogicalUnitWriter to set the obj.id = "" just so I could get this deployed.
> It turns out that the lun used for the 1st installation has hex letters in the lun id but the lun for the 2nd installation is made entirely of the digits 0-9.
> 
> I have logs available if needed but it would appear to be something to do with the handling of an all base-10 lun id?
> 
> I'm using:
> python-ovirt-engine-sdk4-4.3.4-2.el7.x86_64
> ovirt-hosted-engine-setup-2.3.13-1.0.1.el7.noarch
> 
> On Oracle Linux 7

Hi @graham-collinson, 
Can you please provide, ovirt-hosted-engine-setup logs, ovirt-ansible-hosted-engine-setup version, and ansible version?

**Comment by graham-collinson** [comment]
relevant portion of the log /var/log/ovirt-hosted-engine-setup/ovirt-hosted-engine-setup-ansible-create_storage_domain-202153153917-sflb1e.log:
2021-06-03 15:39:46,237+0100 DEBUG var changed: host "localhost" var "otopi_storage_domain_details_fc" type "<type 'dict'>" value: "{
    "changed": false,
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ovirt_storage_domain_payload_KmcGJR/__main__.py\", line 743, in main\n    ret = storage_domains_module.create()\n  File \"/tmp/ansible_ovirt_storage_domain_payload_KmcGJR/ansible_ovirt_storage_domain_payload.zip/ansible/module_utils/ovirt.py\", line 610, in create\n    **kwargs\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py\", line 25564, in add\n    return self._internal_add(storage_domain, headers, query, wait)\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py\", line 222, in _internal_add\n    request.body = writer.Writer.write(object, indent=True)\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/writer.py\", line 189, in write\n    writer(obj, cursor, root)\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py\", line 8959, in write_one\n    HostStorageWriter.write_one(obj.storage, writer, 'storage')\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py\", line 4288, in write_one\n    LogicalUnitWriter.write_many(obj.logical_units, writer, 'logical_unit', 'logical_units')\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py\", line 5301, in write_many\n    LogicalUnitWriter.write_one(obj, writer, singular)\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py\", line 5250, in write_one\n    writer.write_attribute('id', obj.id)\nTypeError: The 'value' parameter must be a string\n",
    "failed": true,

There was also a file /tmp/create_storage_domain_out.json that had the same traceback details and included the module_args.  The args had "fcp": {"lun_id": 1234} i.e. no quotes around the all digit lun id.

ovirt-ansible-hosted-engine-setup-1.0.32-1.0.5.el7.noarch
ansible-2.8.4-1.el7.noarch

The process that was being run at the time was like this:
/usr/bin/python2 /usr/bin/ansible-playbook -e @/var/lib/ovirt-hosted-engine-setup/cockpit/ansibleVarFilejlnKjK.var /usr/share/ovirt-hosted-engine-setup/ansible/trigger_role.yml --module-path=/usr/share/ovirt-hosted-engine-setup/ansible --inventory=localhost, --tags=create_storage_domain --skip-tags=always -e @/var/tmp/ovirt-hosted-engine-setup/cockpit/create_storage-202153161141-lnghj9.pipe

If I ran the above command with a copy of the ansible var file it would hit the same issue

**Comment by arachmani** [comment]
I'm closing it since oVirt 4.3 is not supported, upgrading to 4.4 is highly recommended.
In case you encounter this issue in oVirt 4.4, feel free to reopen.
