### ISSUE TITLE
Bond interfaces cannot actually have ipv4 or ipv6 addresses but 001_validate_network_interfaces.yml requires it?

### ISSUE THREAD

**Issue by kbrowder** [oVirt/ovirt-ansible-collection#192]
##### SUMMARY
So I'm looking at the logic in 001_validate_network_interfaces.yml trying to figure out why my 802.3ad bond0 (with bridge0) doesn't work even though it seems to work fine on the host.

Looking at the logic it seems to require an ipv4 or ipv6 address.  At least on Enterprise Linux 8, bonds seem to not be able to even have ip addresses, that's a property of any associated bridges.
Specifically I think a bond cannot with nmcli cannot have ipv4.* or ipv6.* parameters.  You need a bridge for that.

I'm not exactly sure what the correct fix is, probably just to allow using a bridge on a bond that fits the supported criteria?

**Comment by arachmani** [comment]
@kbrowder We need to check that. 
Can you please share the Ansible version and logs from `/var/log/ovirt-hosted-engine-setup` that include the failure?

**Comment by kbrowder** [comment]
Sure, ansible version is in the logs but apparently it's 2.9.15
[ovirt-hosted-engine-setup-ansible-get_network_interfaces-20201210102337-7ld366.log](https://github.com/oVirt/ovirt-ansible-collection/files/5673791/ovirt-hosted-engine-setup-ansible-get_network_interfaces-20201210102337-7ld366.log)

**Comment by dominikholler** [comment]
@kbrowder
Is this issue about a problem during deploying oVirt hosted engine?
If so, can you please re-try without bridge0 and assign the IP address directly to bond0?

**Comment by arachmani** [comment]
@kbrowder Did you try @dominikholler's suggestion - https://github.com/oVirt/ovirt-ansible-collection/issues/192#issuecomment-756130718?

**Comment by arachmani** [comment]
@kbrowder Unfortunately, we are unable to help without your input.
Please reopen/open a new issue if you encounter this again.
