### ISSUE TITLE
How to best implement a rolling reboot?

### ISSUE THREAD

**Issue by jake2184** [oVirt/ovirt-ansible-collection#201]
##### SUMMARY
I am trying to implement a rolling reboot of cluster nodes

I can do this via (serially over all hosts):
- oivrt_host:
     state: maintenance
- ovirt_host:
     state: stopped
- Pause for 180 seconds
- ovirt_host:
      state: started

However, this requires a long pause between stopping and starting, otherwise the start command is rejected by oVirt (which has a 180s timeout for the first power management action to complete).

I have tried using `state: restarted`, but this doesn't work with the host being in maintenance mode, as the module waits for state to be UP, whereas after the reboot it comes back in maintenance mode. I want to use maintenance mode to ensure VMs are gracefully moved away before powering down the host

What is the best approach here, to do a rolling reboot with minimal delay?

##### COMPONENT NAME
ovirt_host module

**Comment by mwperina** [comment]
Using `status: restarted` should work, but we have a bug there, we need to get current state (either Maintenance or Up) and then wait to get into the status:

https://github.com/oVirt/ovirt-ansible-collection/blob/master/plugins/modules/ovirt_host.py#L661

Until above is fixed, you need to use above code, but you can decrease the timeout to 60 seconds using:

```
engine-config -s FenceQuietTimeBetweenOperationsInSec=60
```

**Comment by jake2184** [comment]
Ace, thanks. I'll change that config as a workaround, but can we leave this open as a bug?

**Comment by mwperina** [comment]
Of course, we will try to include the fix into the next collection release
