### ISSUE TITLE
ovirt_disk should mention qemu-img in requirements

### ISSUE THREAD

**Issue by nesanton** [oVirt/ovirt-ansible-collection#203]
##### SUMMARY

ovirt_disk may fail if qemu-img is not installed, but requirements don't mention it

##### COMPONENT NAME

ovirt_disk module

**Comment by dmc5179** [comment]
I also ran into this issue. I received this error message until I install the qemu-img RPM package.

```
[Errno 2] No such file or directory: 'qemu-img': 'qemu-img'
```

**Comment by mnecas** [comment]
Hi @nesanton and @dmc5179,
thanks for the info. 
I was thinking to add it to requirements.txt but it is used for PyPI installation and the package is not there so I'll update the docs of the module.
Currently, it's automatically installed if you install the collection from RPM, and later it should be also installed from the galaxy as well (after ansible-builder implementation [1]).
[1] https://github.com/ansible/ansible-builder
