### ISSUE TITLE
Provide an option/module to discover iSCSI targets from oVirt Engine RESTAPI

### ISSUE THREAD

**Issue by arachmani** [oVirt/ovirt-ansible-collection#213]
We have oVirt Engine RESTAPI endpoint to discover iSCSI targets -
http://ovirt.github.io/ovirt-engine-api-model/4.4/#services/host/methods/iscsi_discover

We need the option to get this information using Ansible module by providing the host id.

**Comment by mnecas** [comment]
It is already implemented in the `ovirt_host` module.
https://docs.ansible.com/ansible/latest/collections/ovirt/ovirt/ovirt_host_module.html#parameter-iscsi

**Comment by arachmani** [comment]
> Asaf, are there any gaps in current ovirt_host implementation? If not, could you please close this issue?
> 
> @arachmani

@mwperina, we use `iscsi_details` from REST API which contains: address, portal, port, and target, while `ovirt_host` gives us only `iscsi_target` which contains only target.
I'm checking if we can use `ovirt_host_storage_info` with https://github.com/oVirt/ovirt-ansible-collection/pull/214

**Comment by arachmani** [comment]
`ovirt_host_storage_info` doesn't help, we need the same parameters as we get from `iscsi_details`.

**Comment by mnecas** [comment]
For this issue I created https://bugzilla.redhat.com/show_bug.cgi?id=1926819

**Comment by mnecas** [comment]
Now there is a new resp parameter when doing discover iSCSI with `ovirt_host` and that is `iscsi_targets_struct` which contains all information around the targets and at the same time keeps parameter `iscsi_targets` simple list of targets for backwards compatibility
