### ISSUE TITLE
issue when running under ansible 2.10

### ISSUE THREAD

**Issue by kristvanbesien** [oVirt/ovirt-ansible-collection#240]
##### SUMMARY

ovirt_net requires name to be set when using ansible 2.10

##### COMPONENT NAME

role hosted_engine_setup

##### STEPS TO REPRODUCE

Try to use the hosted_engine_setup rol from a workstation that uses ansible 2.10

##### EXPECTED RESULTS

Role executes without issues.

##### ACTUAL RESULTS

Get the following error:

```
TASK [redhat.rhv.hosted_engine_setup : Get libvirt interfaces] *********************************************************************************************************
fatal: [mgg-rht001-fra05.mgg.local]: FAILED! => {"changed": false, "msg": "missing required arguments: name"}
```

From Ansible 2.10 onwards the "name" paramter is mandatory for ovirt_net. 

The tasks used by the hosted-engine-setup role (and maybe others)  contain a lot of instances of:

```
- name: Get libvirt interfaces
    virt_net:
      command: facts
```

This is the source of the error, as a "name" parameter should be added.

**Comment by mnecas** [comment]
Hi @kristvanbesien,
did a bit of research and found out that the issue was already resolved and released [1].
(It probably takes some time to update the collections which are installed with ansible.)

I'll add the `community.libvirt` latest version as a requirement.

[1] https://github.com/ansible-collections/community.libvirt/commit/9f6a5282b5a400dc87b7be34006618d5b136d980

**Comment by arachmani** [comment]
Based on [1], we are not supporting Ansible 2.10.
@mwperina Can you please confirm?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1885327#c1

**Comment by mwperina** [comment]
RHV officially doesn't support any ansbile version higher than 2.9, but we are trying to fix breakages which would prevent using oVirt Ansible Collection with newer versions. If we wouldn't do that, than oVirt Ansible Collection couldn't be part of those newer Ansible releases

**Comment by kristvanbesien** [comment]
The documentation for the ovirt-ansible colleciton mentions under requirements: "Ansible version 2.9.11 or higher". This suggests that the collection would work under 2.10. If 2.10 is not supported this should be mentioned.

**Comment by mwperina** [comment]
oVirt Ansible Collection is included in both oVirt and RHV and for both we fully support only Ansible 2.9. So collection might work on Ansible 2.10 (and we believe that most of modules work fine), but for example hosted_engine_setup role is clearly tight to oVirt/RHV installation, so you need to use the oVirt/RHV requirements.

**Comment by arachmani** [comment]
Requirements for `hosted_engine_setup` role has been updated -
https://github.com/oVirt/ovirt-ansible-collection/tree/master/roles/hosted_engine_setup#requirements
