### ISSUE TITLE
ovirtsdk4 version 4.4.0 or higher is required for this module

### ISSUE THREAD

**Issue by jasonnykamp** [oVirt/ovirt-ansible-collection#245]
Hi I just installed the sdk via rpm on CentOS 8 with ansible 2.10 and python3 and it is still throwing this error. Any thoughts on why?

**Comment by jasonnykamp** [comment]
I also get this
```
>>> import ovirtsdk4.version as sdk_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ovirtsdk4'
>>> 
```

**Comment by mnecas** [comment]
Hi @jasonnykamp,
which version of SDK have you installed?
`rpm -qa "python3-ovirt-engine-sdk4"`

**Comment by jasonnykamp** [comment]
python3-ovirt-engine-sdk4-4.4.10-1.el8.x86_64

I think it may have installed into the systems python packages and not into my pyvenv. Any idea how best to get it into the venv?

**Comment by jasonnykamp** [comment]
I ended up recreating my venv with --system-site-packages enabled and it works. 

Thanks for your help. Closing.
