### ISSUE TITLE
[RFE] add the option to deploy the hosted engine when the DWH deploy on different machine

### ISSUE THREAD

**Issue by kobihk** [oVirt/ovirt-ansible-collection#260]
Since there are situations that we need the DWH on a different machine
the current option is to do the regular deploy and just after it complete to do the following:
https://www.ovirt.org/documentation/data-warehouse/Migrating_Data_Warehouse_to_a_Separate_Machine.html#migrating-the-data-warehouse-service-to-a-separate-machine

it will be great if we have this option in the deployment process.

**Comment by sandrobonazzola** [comment]
Closing deferred due to capacity. Feel free to reopen if you have capacity for handling it.
