### ISSUE TITLE
HostedEngine: Wait for the local bootstrap VM to be down at engine eyes

### ISSUE THREAD

**Issue by rootameen** [oVirt/ovirt-ansible-collection#262]
Hello,
on a fresh hostedengine setup [4.3.9], using `ovirt-hosted-engine-deploy`, the setup fails at following step:

    [ INFO  ] TASK [ovirt.hosted_engine_setup : Wait for the local bootstrap VM to be down at engine eyes]
    [ ERROR ] fatal: [localhost]: FAILED! => {"ansible_facts": {"ovirt_vms": [{"affinity_labels": [], "applications": [], "bios": {"boot_menu": {"enabled": false}, "type": "i440fx_sea_bios"}, "cdroms": [], "cluster"
    : {"href": "/ovirt-engine/api/clusters/33428f36-67c0-11eb-86e4-00163e5d0328", "id": "33428f36-67c0-11eb-86e4-00163e5d0328"}, "comment": "", "cpu": {"architecture": "x86_64", "topology": {"cores": 1, "sockets": 4
    , "threads": 1}}, "cpu_profile": {"href": "/ovirt-engine/api/cpuprofiles/58ca604e-01a7-003f-01de-000000000250", "id": "58ca604e-01a7-003f-01de-000000000250"}, "cpu_shares": 0, "creation_time": "2021-02-05 17:48:
    51.621000+03:00", "delete_protected": false, "description": "", "disk_attachments": [], "display": {"address": "127.0.0.1", "allow_override": false, "certificate": {"content": "-----BEGIN CERTIFICATE-----\nMIIDq
    DCCApCgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxEjAQBgNVBAoM\nCWFtZWVuLmxhYjEcMBoGA1UEAwwTb2hlLmFtZWVuLmxhYi44NzkzNTAeFw0yMTAyMDQxNDQwMjha\nFw0zMTAyMDMxNDQwMjhaMD8xCzAJBgNVBAYTAlVTMRIwEAYDVQQKDAlhbWVl
    bi5sYWIxHDAaBgNV\nBAMME29oZS5hbWVlbi5sYWIuODc5MzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDo\nh/Ne5o5qCXVUa/5REOm5dh0J3EogXqTJIpbTQaMxrlvdBN+HnqqqEv72+LQqEB7evkCR4AjFwfns\nFSh+cVNn0m1M2WI8YlKAR6Y5lDQaOkLzbffy6
    l8rqCyBGS4jTUzfyBnRM0U4SR/JzCG02bFta/6W\nT8xdUsgYA6K/T+H7D9AfZ5bKSZZn4e1WAzFMvopBp5Je/bo1bt3dsssO10BVQgBl93ijN/bjrZ9M\nfr79mRrsenyivmbthLGe8fipCrrdzIde6j9169ZtE6i1vpt1kI28t/x7qgJ1wqtrMHntZMRt18hv\n5dimnKIAkKxyL5
    gQ0Z8A1e/EsBcpVde8gDIpAgMBAAGjga0wgaowHQYDVR0OBBYEFEAQ8KYM4vbR\nZ0g2SllvSiB16VW4MGgGA1UdIwRhMF+AFEAQ8KYM4vbRZ0g2SllvSiB16VW4oUOkQTA/MQswCQYD\nVQQGEwJVUzESMBAGA1UECgwJYW1lZW4ubGFiMRwwGgYDVQQDDBNvaGUuYW1lZW4ubGFiL
    jg3OTM1\nggIQADAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEA\nMdp8mT5oCB9LGFUtocVa7NkkPOoI2bjw3D1h8mOAYs1FfQh+tXtyJyK4Swv9W1aqg+AmT7/YCwox\nDb+16Hh7J+Nn+K1DFTOjM5kM77Um7eQEcPaiGuuxYpcNQ7
    mvW5nwbU1eyxuWL9wklZ2On/9sCYZM\n9LaXzzLmKjtLa2IppVq9xj++W/EepTSKGcreQAMjVwswWEesBla09MxqRo6wt432wnlNprFWhff3\nsvy7xnPYeNB6MPR3jfgz74vFEj2KB2BmzI4vMdDfe/osljgRU72NmslS9kG5MnqHA4W7WM119Txs\n4BBulA+fs8PGfBoE89A4f8L
    kvJduXIasIm5Y+A==\n-----END CERTIFICATE-----\n", "organization": "root.lab", "subject": "O=root.lab,CN=ovirtvlk.root.lab"}, "copy_paste_enabled": true, "disconnect_action": "LOCK_SCREEN", "file_transfer_enabl
    ed": true, "monitors": 1, "port": 5900, "single_qxl_pci": false, "smartcard_enabled": false, "type": "vnc"}, "fqdn": "ohe.root.lab", "graphics_consoles": [], "guest_operating_system": {"architecture": "x86_64",
     "codename": "", "distribution": "CentOS Linux", "family": "Linux", "kernel": {"version": {"build": 0, "full_version": "3.10.0-1127.8.2.el7.x86_64", "major": 3, "minor": 10, "revision": 1127}}, "version": {"full
    _version": "7", "major": 7}}, "guest_time_zone": {"name": "+03", "utc_offset": "+03:00"}, "high_availability": {"enabled": false, "priority": 0}, "host": {"href": "/ovirt-engine/api/hosts/5fb34978-611e-4ac5-8694
    -0de6ac9d984c", "id": "5fb34978-611e-4ac5-8694-0de6ac9d984c"}, "host_devices": [], "href": "/ovirt-engine/api/vms/87d130f8-d9ea-4a4a-b462-831ec1c8e8c1", "id": "87d130f8-d9ea-4a4a-b462-831ec1c8e8c1", "io": {"thre
    ads": 1}, "katello_errata": [], "large_icon": {"href": "/ovirt-engine/api/icons/7fc8b9b9-8f53-4398-8966-325fd213796e", "id": "7fc8b9b9-8f53-4398-8966-325fd213796e"}, "memory": 17179869184, "memory_policy": {"gua
    ranteed": 17179869184, "max": 17179869184}, "migration": {"auto_converge": "inherit", "compressed": "inherit"}, "migration_downtime": -1, "multi_queues_enabled": true, "name": "external-HostedEngineLocal", "next
    _run_configuration_exists": false, "nics": [], "numa_nodes": [], "numa_tune_mode": "interleave", "origin": "external", "original_template": {"href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000
    000", "id": "00000000-0000-0000-0000-000000000000"}, "os": {"boot": {"devices": ["hd"]}, "type": "other"}, "permissions": [], "placement_policy": {"affinity": "migratable"}, "quota": {"id": "47ed64c4-67c0-11eb-b
    2a7-00163e5d0328"}, "reported_devices": [], "run_once": false, "sessions": [], "small_icon": {"href": "/ovirt-engine/api/icons/46aee8db-4af0-4ed9-b10b-e3e73ae9b881", "id": "46aee8db-4af0-4ed9-b10b-e3e73ae9b881"}
    , "snapshots": [], "sso": {"methods": [{"id": "guest_agent"}]}, "start_paused": false, "stateless": false, "statistics": [], "status": "unknown", "storage_error_resume_behaviour": "auto_resume", "tags": [], "tem
    plate": {"href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000", "id": "00000000-0000-0000-0000-000000000000"}, "time_zone": {"name": "Etc/GMT"}, "type": "desktop", "usb": {"enabled": false},
     "watchdogs": []}]}, "attempts": 24, "changed": false, "deprecations": [{"msg": "The 'ovirt_vm_facts' module has been renamed to 'ovirt_vm_info', and the renamed one no longer returns ansible_facts", "version":
    "2.13"}]}
    [ ERROR ] Failed to execute stage 'Closing up': Failed executing ansible-playbook

Then it goes in to some cleanups and fails. The dashboard for the engine is available though, I tried cleaning up and redoing the process, but it always fails in the exact same spot.

I checked all of the logs and did not find anything clear that shows why the facts are failing:

    2021-02-05 18:06:33,299+0300 ERROR otopi.ovirt_hosted_engine_setup.ansible_utils ansible_utils._process_output:107 fatal: [localhost]: FAILED! => {"ansible_facts": {"ovirt_vms": [{"affinity_labels": [], "applica
    tions": [], "bios": {"boot_menu": {"enabled": false}, "type": "i440fx_sea_bios"}, "cdroms": [], "cluster": {"href": "/ovirt-engine/api/clusters/33428f36-67c0-11eb-86e4-00163e5d0328", "id": "33428f36-67c0-11eb-86
    e4-00163e5d0328"}, "comment": "", "cpu": {"architecture": "x86_64", "topology": {"cores": 1, "sockets": 4, "threads": 1}}, "cpu_profile": {"href": "/ovirt-engine/api/cpuprofiles/58ca604e-01a7-003f-01de-000000000
    250", "id": "58ca604e-01a7-003f-01de-000000000250"}, "cpu_shares": 0, "creation_time": "2021-02-05 17:48:51.621000+03:00", "delete_protected": false, "description": "", "disk_attachments": [], "display": {"addre
    ss": "127.0.0.1", "allow_override": false, "certificate": {"content": "-----BEGIN CERTIFICATE-----\nMIIDqDCCApCgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwPzELMAkGA1UEBhMCVVMxEjAQBgNVBAoM\nCWFtZWVuLmxhYjEcMBoGA1UEAwwTb2hlL
    mFtZWVuLmxhYi44NzkzNTAeFw0yMTAyMDQxNDQwMjha\nFw0zMTAyMDMxNDQwMjhaMD8xCzAJBgNVBAYTAlVTMRIwEAYDVQQKDAlhbWVlbi5sYWIxHDAaBgNV\nBAMME29oZS5hbWVlbi5sYWIuODc5MzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDo\nh/Ne5o5qCX
    VUa/5REOm5dh0J3EogXqTJIpbTQaMxrlvdBN+HnqqqEv72+LQqEB7evkCR4AjFwfns\nFSh+cVNn0m1M2WI8YlKAR6Y5lDQaOkLzbffy6l8rqCyBGS4jTUzfyBnRM0U4SR/JzCG02bFta/6W\nT8xdUsgYA6K/T+H7D9AfZ5bKSZZn4e1WAzFMvopBp5Je/bo1bt3dsssO10BVQgBl9
    3ijN/bjrZ9M\nfr79mRrsenyivmbthLGe8fipCrrdzIde6j9169ZtE6i1vpt1kI28t/x7qgJ1wqtrMHntZMRt18hv\n5dimnKIAkKxyL5gQ0Z8A1e/EsBcpVde8gDIpAgMBAAGjga0wgaowHQYDVR0OBBYEFEAQ8KYM4vbR\nZ0g2SllvSiB16VW4MGgGA1UdIwRhMF+AFEAQ8KYM4v
    bRZ0g2SllvSiB16VW4oUOkQTA/MQswCQYD\nVQQGEwJVUzESMBAGA1UECgwJYW1lZW4ubGFiMRwwGgYDVQQDDBNvaGUuYW1lZW4ubGFiLjg3OTM1\nggIQADAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEA\nMdp8mT5oCB9LGFUtocV
    a7NkkPOoI2bjw3D1h8mOAYs1FfQh+tXtyJyK4Swv9W1aqg+AmT7/YCwox\nDb+16Hh7J+Nn+K1DFTOjM5kM77Um7eQEcPaiGuuxYpcNQ7mvW5nwbU1eyxuWL9wklZ2On/9sCYZM\n9LaXzzLmKjtLa2IppVq9xj++W/EepTSKGcreQAMjVwswWEesBla09MxqRo6wt432wnlNprFWhf
    f3\nsvy7xnPYeNB6MPR3jfgz74vFEj2KB2BmzI4vMdDfe/osljgRU72NmslS9kG5MnqHA4W7WM119Txs\n4BBulA+fs8PGfBoE89A4f8LkvJduXIasIm5Y+A==\n-----END CERTIFICATE-----\n", "organization": "root.lab", "subject": "O=root.lab,CN=o
    virtvlk.root.lab"}, "copy_paste_enabled": true, "disconnect_action": "LOCK_SCREEN", "file_transfer_enabled": true, "monitors": 1, "port": 5900, "single_qxl_pci": false, "smartcard_enabled": false, "type": "vnc"
    }, "fqdn": "ohe.root.lab", "graphics_consoles": [], "guest_operating_system": {"architecture": "x86_64", "codename": "", "distribution": "CentOS Linux", "family": "Linux", "kernel": {"version": {"build": 0, "fu
    ll_version": "3.10.0-1127.8.2.el7.x86_64", "major": 3, "minor": 10, "revision": 1127}}, "version": {"full_version": "7", "major": 7}}, "guest_time_zone": {"name": "+03", "utc_offset": "+03:00"}, "high_availabili
    ty": {"enabled": false, "priority": 0}, "host": {"href": "/ovirt-engine/api/hosts/5fb34978-611e-4ac5-8694-0de6ac9d984c", "id": "5fb34978-611e-4ac5-8694-0de6ac9d984c"}, "host_devices": [], "href": "/ovirt-engine/
    api/vms/87d130f8-d9ea-4a4a-b462-831ec1c8e8c1", "id": "87d130f8-d9ea-4a4a-b462-831ec1c8e8c1", "io": {"threads": 1}, "katello_errata": [], "large_icon": {"href": "/ovirt-engine/api/icons/7fc8b9b9-8f53-4398-8966-32
    5fd213796e", "id": "7fc8b9b9-8f53-4398-8966-325fd213796e"}, "memory": 17179869184, "memory_policy": {"guaranteed": 17179869184, "max": 17179869184}, "migration": {"auto_converge": "inherit", "compressed": "inher
    it"}, "migration_downtime": -1, "multi_queues_enabled": true, "name": "external-HostedEngineLocal", "next_run_configuration_exists": false, "nics": [], "numa_nodes": [], "numa_tune_mode": "interleave", "origin":
     "external", "original_template": {"href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000", "id": "00000000-0000-0000-0000-000000000000"}, "os": {"boot": {"devices": ["hd"]}, "type": "other"},
     "permissions": [], "placement_policy": {"affinity": "migratable"}, "quota": {"id": "47ed64c4-67c0-11eb-b2a7-00163e5d0328"}, "reported_devices": [], "run_once": false, "sessions": [], "small_icon": {"href": "/ov
    irt-engine/api/icons/46aee8db-4af0-4ed9-b10b-e3e73ae9b881", "id": "46aee8db-4af0-4ed9-b10b-e3e73ae9b881"}, "snapshots": [], "sso": {"methods": [{"id": "guest_agent"}]}, "start_paused": false, "stateless": false,
     "statistics": [], "status": "unknown", "storage_error_resume_behaviour": "auto_resume", "tags": [], "template": {"href": "/ovirt-engine/api/templates/00000000-0000-0000-0000-000000000000", "id": "00000000-0000-
    0000-0000-000000000000"}, "time_zone": {"name": "Etc/GMT"}, "type": "desktop", "usb": {"enabled": false}, "watchdogs": []}]}, "attempts": 24, "changed": false, "deprecations": [{"msg": "The 'ovirt_vm_facts' modu
    le has been renamed to 'ovirt_vm_info', and the renamed one no longer returns ansible_facts", "version": "2.13"}]}
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/otopi/context.py", line 132, in _executeMethod
        method['method']()
      File "/usr/share/ovirt-hosted-engine-setup/scripts/../plugins/gr-he-ansiblesetup/core/target_vm.py", line 235, in _closeup
        r = ah.run()
      File "/usr/lib/python2.7/site-packages/ovirt_hosted_engine_setup/ansible_utils.py", line 229, in run
        raise RuntimeError(_('Failed executing ansible-playbook'))
    RuntimeError: Failed executing ansible-playbook
    2021-02-05 18:06:34,003+0300 ERROR otopi.context context._executeMethod:154 Failed to execute stage 'Closing up': Failed executing ansible-playbook

Any thoughts?

**Comment by arachmani** [comment]
Hi @rootameen, did you try https://github.com/oVirt/ovirt-ansible-collection/issues/262#issuecomment-782979400?

**Comment by rootameen** [comment]
Hi @arachmani 
Apologies for not reporting back. I've tried that with no luck, and no longer have oVirt setup to debug this any further.

**Comment by arachmani** [comment]
Thanks for the update, I'm closing it since we don't have the full logs, and oVirt 4.3 is not supported anymore.
My suggestion is to use the latest oVirt 4.4 version.
Please feel free to reopen this issue if you encounter it again.

**Comment by miltonosses** [comment]
I was able to install the hosted engine after reach the DNS FQDN for engine
