### ISSUE TITLE
Fix changelog's check

### ISSUE THREAD

**Issue by arachmani** [oVirt/ovirt-ansible-collection#405]

**Comment by mwperina** [comment]
Could you please provide the details about the issue?

@arachmani

**Comment by arachmani** [comment]
https://github.com/oVirt/ovirt-ansible-collection/pull/404 is missing changelog but "All checks have passed"
See also https://github.com/oVirt/ovirt-ansible-collection/runs/4497882849?check_suite_focus=true#step:7:245 :
```+ cd /__w/ovirt-ansible-collection/ovirt-ansible-collection
++ git diff --quiet 'HEAD^' ./plugins ./roles
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>```

**Comment by mwperina** [comment]
Issue should be fixed, but to see the results all PRs need to be rebased on top of latest master
