### ISSUE TITLE
ovirt_vm module Add storage_error_resume_behaviour Switch

### ISSUE THREAD

**Issue by hemak88** [oVirt/ovirt-ansible-collection#694]
##### SUMMARY
ovirt_vm ansible module is missing storage_error_resume_behaviour switch parameter.
The feature to choose VM state for HA is available in Ovirt GUI. So same feature if available in ansible makes it more powerful and flexible.
It will be great to have that feature because it can enable choosing the VM state to be in when a hardware or storage issue happens

##### COMPONENT NAME
ovirt_vm
https://docs.ansible.com/ansible/2.9/modules/ovirt_vm_module

##### ADDITIONAL INFORMATION
Example usage once the feature is added:
ovirt_vm:
storage_error_resume_behaviour:
options: "Auto Resume" | "Leave Paused" | "Kill"
Restart required for VM (apply with restart)

**Comment by hemak88** [comment]
Any update on this

**Comment by hemak88** [comment]
Can we add this feature please?

**Comment by michalskrivanek** [comment]
Hi, no one is actively working on new features in the module, if you propose a patch and verify it we can still include it, but it's unlikely someone else would pick it up

**Comment by hemak88** [comment]
Hi @michalskrivanek , I have patch for this which I tested in my lab, Can we add this to the module. How should I go ahead with Pull request creation

**Comment by mnecas** [comment]
If you have some patch please post the PR and I'll check it out. Please also sign the commit with 'git commit -s'.

**Comment by hemak88** [comment]
I have raised a patch. Kindly review @mnecas 
https://github.com/oVirt/ovirt-ansible-collection/pull/721
