### ISSUE TITLE
Can't set storage size limit for quota when using Ansible variables

### ISSUE THREAD

**Issue by hambuergaer** [oVirt/ovirt-ansible-collection#709]
SUMMARY:

The current implementation of this module seems not to be able to set storage size limit quota while using Ansible variables like e.g.  "{{ storage_size }}"

It seems that "limit=storage.get('size')" must be "limit=int(storage.get('size'))" instead.

https://github.com/oVirt/ovirt-ansible-collection/blob/9befbcf12fd942a961daca9ab3aaa178a59cd76d/plugins/modules/ovirt_quota.py#L312C31-L312C50

**Comment by mnecas** [comment]
Hi! I apologize for the late reply. 
Thanks for the issue and the PR! I tried to update your original PR but once I pushed it to your branch it for some reason closed the PR. So I created a new one.

**Comment by hambuergaer** [comment]
Hi @mnecas, no worries! Thank you for keeping an eye on that. Can you already estimate when this change will be released in the next version? It seems that Ansible lint still finds some errors: https://github.com/oVirt/ovirt-ansible-collection/actions/runs/5595712007/job/15156737978?pr=712

Best regards

Frank
