### ISSUE TITLE
License conflict?

### ISSUE THREAD

**Issue by resmo** [oVirt/ovirt-ansible-collection#87]
##### SUMMARY

I noticed your license is Apache2 but a lot of plugins and content is under GPL. This needs clarification.

**Comment by mwperina** [comment]
Thanks for pointing out, even though oVirt project prefers Apache 2.0 license, we were needed to to use GPL license for Ansible module.

Martine, could you please go over all files in the repo and check its licenses? If there are multiple licenses, we need to mention them all, but most probably majority of them is licensed under GPL

@mnecas @dangel101
